### ISSUE TITLE
[v10xx] Reorganize databases

### ISSUE THREAD

**Issue by selcukcukur** [selcukcukur/OpenKO#2]
## Description

It makes the most sense to walk with a certain standard in terms of the safety and sustainability of the project. In line with this idea, multiple databases will be created in order to divide the databases into parts, making it difficult for aggressive actions and not to impose the cost of a single mistake on all databases.

Thus, the developer who needs to make any improvement will only be able to access the data of the database he is responsible for and will be able to handle his transactions without accessing other databases. 

This reduces possible data theft and similar activities to some extent and provides ease of management for officially published game projects in the future.

Every database created in line with these ideas should have certain standards.

### Rules

- Database names must follow `UpperFlatCase` rules.
- Database user names must follow `UpperFlatCase` rules.

## Tasks

1. Divide the database into a total of four parts.

    - [x] **OPENKO_ACCOUNT** (It is the database that will contain general data about account information)
    - [x] **OPENKO_COMMON** (It is the database that will contain general data about the game)
    - [x] **OPENKO_LOG** (It is the database where error, information, warning and all other log records will be located)
    - [x] **OPENKO_SERVER** (It is the database that will contain general data about the server)

2. Separate users will be created for each database.

    - [x] **OPENKO_ACCOUNT_USER** (It will be created automatically with powershell scripts)
    - [x] **OPENKO_COMMON_USER** (It will be created automatically with powershell scripts)
    - [x] **OPENKO_LOG_USER** (It will be created automatically with powershell scripts)
    - [x] **OPENKO_SERVER_USER** (It will be created automatically with powershell scripts)

3. Separate ODBC resource will be created for each database.

    - [x] **OPENKO_ACCOUNT** (It will be created automatically with powershell scripts)
    - [x] **OPENKO_COMMON** (It will be created automatically with powershell scripts)
    - [x] **OPENKO_LOG** (It will be created automatically with powershell scripts)
    - [x] **OPENKO_SERVER** (It will be created automatically with powershell scripts)

4. Automatically import and export with powershell script.

    - [x] **Database** (Import and export operations will be automatic)
    - [x] **Table** (Import and export operations will be automatic)
    - [x] **Procedure** (Import and export operations will be automatic)
    - [x] **Data** (Import and export operations will be automatic)

**Comment by selcukcukur** [comment]
For detailed information, see :  https://github.com/selcukcukur/OpenKO/commit/8e15649ccfe6ee02930ab2ee24b0447e91cbb889
