### ISSUE TITLE
[v10xx] Reorganize database tables

### ISSUE THREAD

**Issue by selcukcukur** [selcukcukur/OpenKO#3]
## Description

Database tables need to be rebuilt and all columns and data types must be checked and matched, as well as providing all logically usable additions and updating them in the form of server, client and database. After these changes are made, we will have a cleaner and more understandable structure and we will have taken confident and good steps in the progress of the project.

### Rules

- Database table names must apply `UpperFlatCase` rules
- Database column names must follow the `StudlyCaps` convention.
- Database procedure names must follow the `UpperFlatCase` convention.
- Database tables must be named `singular`.

## Tasks

- [ ] Fixes logical errors in database tables.
- [ ] Fixes logical errors in database procedures.
- [ ] Solve any existing logical problems in the database.
- [ ] Apply all changes made to the database to dependent projects.
