### ISSUE TITLE
[v10xx] Support all image formats

### ISSUE THREAD

**Issue by selcukcukur** [selcukcukur/OpenKO#4]
## Description

Supporting every visual extension of the game engine will provide a good advantage in the future. In this way, it will be possible to provide better quality images at lower sizes in an easy to use format. Although bitmap images are currently used, we should make it possible to support other formats in the future and leave it entirely to the developer's preference.

```mermaid
flowchart
    subgraph Image Process
    Image-->TypeDetection
    TypeDetection-->JPG
    TypeDetection-->BMP
    TypeDetection-->PNG
    TypeDetection-->GIF
    JPG-->Process
    BMP-->Process
    PNG-->Process
    GIF-->Process
    Process-->Show
    Process-->Load
    Process-->Save
    end
```

For a more illustrative example, I have presented you a diagram above. If all images are processed in this way, it will be easier for us to manage processes and we can work flexibly by supporting all extensions.

## Tasks

- [ ] Create a base class for images.
- [ ] Ensure processing by appropriate type from the created base class.
- [ ] Make sure the texture files support all formats.
- [ ] Make sure it supports bitmap, png, jpeg and gif formats.
