### ISSUE TITLE
[v10xx] Support all audio formats

### ISSUE THREAD

**Issue by selcukcukur** [selcukcukur/OpenKO#7]
## Description

Currently, the game engine already supports wav files. Audio files have many extensions but there are a few commonly used formats in general and we should apply the architectural structure to the audio files so that the developer is not dependent on a single format. In the future, when new formats that we can obtain sound quality and low size in come out, we can easily include them in the project.

```mermaid
flowchart
    subgraph Sound Process
    Sound-->TypeDetection
    TypeDetection-->MP3
    TypeDetection-->OGG
    TypeDetection-->WAV
    MP3-->Process
    OGG-->Process
    WAV-->Process
    Process-->Load
    Process-->Play
    Process-->Stop
    end
```

For a more illustrative example, I have presented you a diagram above. If all images are processed in this way, it will be easier for us to manage processes and we can work flexibly by supporting all extensions.

## Tasks

- [ ] Create a base class for audio.
- [ ] Ensure processing by appropriate type from the created base class.
- [ ] Make sure the project files support all formats.
- [ ] Make sure it supports mp3, ogg and wav formats.
