### ISSUE TITLE
[v10xx] Upgrade to DirectX 11!

### ISSUE THREAD

**Issue by selcukcukur** [selcukcukur/OpenKO#8]
## Description

I know this will be very difficult with the current structure. However, we are working on files with a very backward structure. In the 2000's DirectX8 or DirectX9 was great, but now it's really outdated and will probably be out of support for most operating systems soon. I think it should be strongly upgraded as it will provide better performance in speed and optimization and have toolkits that provide convenience in many aspects.

However, this process must be carried out very carefully and in a controlled manner. Texture formats are not suitable for DirectX 11 and must be applied up-to-date by converting the formats of all textures and carefully checking all methods.

I actually opened this discussion to get ideas from the community because there are still some points that I can't resolve about how to use the files in our own custom formats like the current game engine and move the whole game engine to the DirectX 11 version.

I am open to all opinions and ideas on this subject.

## Tasks

- [ ] Apply all changes from DirectX9 to DirectX11 to the project.
- [ ] Make sure you configure the entire project to run through the DirectX 11 graphics pipe.
- [ ] Make sure the game engine, client and tools are still running stably.
